Update 010-shadowed-trait-object-method.md
remove the docs no longer valid, it will lead to compile error below seems it only resolve to trait method
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a298a71d069df17aa097457e07debfe4


Compiling playground v0.0.1 (/playground)
error[E0782]: trait objects must include the `dyn` keyword
  --> src/main.rs:18:5
   |
18 |     Trait::f(&true);
   |     ^^^^^
   |
help: add `dyn` keyword before this trait